/**
 * AUTO-GENERATED by scripts/import-hnm.mjs — don't edit by hand.
 *
 * Real product names and descriptions from the Kaggle H&M "Personalized Fashion
 * Recommendations" dataset. Categories listed here replace the placeholder names
 * in lib/catalog.ts; everything else keeps its generated copy.
 *
 * Empty until you run the importer:
 *   node scripts/import-hnm.mjs --data <path-to-extracted-hnm-dataset>
 */
export type HnmProduct = { name: string; description: string };

export const HNM_PRODUCTS: Record<string, HnmProduct[]> = {};
