/**
 * AUTO-GENERATED by scripts/build-image-manifest.mjs — safe to commit, don't edit by hand.
 *
 * Maps a product slug to an ordered list of image paths under /public. To add your
 * own photos: drop files into `public/products/<slug>/` then run `npm run images`.
 * Products without an entry here fall back to keyword placeholder photography.
 */
export const PRODUCT_IMAGES: Record<string, string[]> = {};
